name: GitHub Actions function  # Name of the workflow, displayed in the GitHub Actions UI

on: workflow_dispatch  # This workflow is triggered manually via the GitHub UI

# success(). Returns true if the current job or previous steps have succeeded.
jobs: 
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building..."
    Deply:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              if: ${{ success() }}
              run: echo "Last job was success"
