# This file is located within the same repository
name: calling-reusable-template

on: workflow_dispatch

# In another repository
jobs:
    production-deploy:
      uses: ./.github/workflows/reusable.yml
      with:
        environment: 'production'