# This file is located within the same repository
name: Calling Workflow

on: workflow_dispatch

jobs:
  use-reusable-build:
    uses: ./.github/workflows/reusable.yml  # Reference reusable workflow
    with:
      node-version: '14'  # Pass inputs to the reusable workflow
      environment: 'production'
    secrets:
      ACCESS_KEY_ID: ${{ secrets.GITHUB_TOKEN }}  # Pass secrets to the reusable workflow