name: Push Event for Specific Files or Folders

on:
  push: 
    paths:
      - 'src/**'  # Trigger if files in src folder are modified
      - '*.md'   # Trigger if any markdown file is modified
  workflow_dispatch: # Enable manual trigger

jobs:
  specific-files-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print affected files
      run: echo "This workflow runs only when files in src/ or markdown files are modified."