# Located in .github/workflows/ci.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      language:
        type: string
        required: true
      build-tool:
        type: string
        required: false
        default: npm
    secrets:
      ACCESS_KEY_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: echo "Setting up for ${{ inputs.language }} with ${{ inputs['build-tool'] }}"

      - name: Install dependencies
        run: |
          if [ ${{ inputs.language }} = "node" ]; then
            npm install
          elif [ ${{ inputs.language }} = "python" ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: echo "Running tests..."

      - name: Deploy with API key
        run: echo "${{ secrets.ACCESS_KEY_ID }}"
