# .github/workflows/resuable.yml
name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to environment
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            echo "Deploying to production server..."
          else
            echo "Deploying to ${{ inputs.environment }} environment..."
          fi  # End the if block properly
