name: Using Secrets

on: workflow_dispatch

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Access secrets
        run: |
          echo "secret is ${{ secrets.ACCESS_KEY_ID }}"