name: Sequential Jobs Example  # The name of the workflow
on: workflow_dispatch  # The workflow can be manually triggered via GitHub UI

jobs:
  job1:  # Define the first job named 'job1'
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu
    steps:
      - name: Job1  # Name of the first step in job1
        run: echo "Running Job 1"  # A shell command to print "Running Job 1" in the logs

  job2:  # Define the second job named 'job2'
    runs-on: ubuntu-latest  # This job also runs on the latest version of Ubuntu
    needs: job1  # This ensures that 'job2' runs only after 'job1' completes
    steps:
      - name: Job2  # Name of the first step in job2
        run: echo "Running Job 2"  # A shell command to print "Running Job 2" in the logs
