name: Sequential Jobs Example
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job2
        run: echo "Running Job 2"